### PR TITLE
web socket connection count fix

### PR DESCRIPTION
**Pull request by nolequen**

### CODE REVIEW

**Comment by tsegismont** [comment]
@nolequen thank you! The changes look good to me. Would you mind to add a test for WebSocket metrics?

**Comment by nolequen** [comment]
@tsegismont, sorry, I don't have enough time to master hawkular server installation. The fix is trivial and I hope it is possible to merge it without appropriate test.

**Comment by tsegismont** [comment]
You don't need to install a Hawkular server, the build will start one for
you.

2017-06-23 13:24 GMT+02:00 Anton Potsyus <notifications@github.com>:

**Comment by nolequen** [comment]
@tsegismont, I've updated the http client metrics test

**Comment by tsegismont** [comment]
@nolequen thank you!

**Pull request merged**
