### PR TITLE
Refactored metrics module, to be able to have additional different backends

### PR DESCRIPTION
**Pull request by dankristensen**
I have done the refactorings, and verified the InfluxDb implementation against a real InfluxDb database, so i know it understands the data correctly.

Please be advised that most of the code has simply been moved into vertx-metric-collect module

### CODE REVIEW

**Comment by vietj** [comment]
can we get a docker CLI in the README that we can run to test against an InfluxDB instance like in this project https://github.com/vert-x3/vertx-mongo-client/ ?

**Comment by dankristensen** [comment]
I have updated with the changes from above conflics

**Comment by tsegismont** [comment]
@dankristensen I'm going to merge your branch into a branch upstream. I'll make a few changes there. Thank you for your contribution, that's a great improvement.

**Comment by tsegismont** [comment]
@dankristensen the upstream branch is `metrics-reporters` You can still contribute changes there. I'll send an email to the vertx-dev group.

**Pull request closed without merging**
